name: React CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "19"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: " CI Failed for ${{ github.repository }}"
          to: ptt24032004@gmail.com, vominhson310805@gmail.com, phamvanminh150204@gmail.com, tranngockhiet22062005@gmail.com
          from: "CI Bot <tranngockhiet22062005@gmail.com>"
          body: |
            CI build failed for commit ${{ github.sha }}.
            From ${{ github.actor }}
            Check details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
